### ISSUE TITLE
Fatal Error with Feeds and Job Scheduler 1.1.1

### ISSUE THREAD

**Issue by t4k** [backdrop-contrib/job_scheduler#3]
Just a note here. I’m getting this error with the latest tagged release of both Feeds and Job Scheduler. It occurs both with an uploaded CSV as well as a CSV available at a URL.
> Error: Class 'JobScheduler’ not found in FeedsSource->scheduleImport() (line 311 of /var/www/backdrop/modules/feeds/includes/FeedsSource.inc).

In order to overcome it I had to download the master branch of `job_scheduler`, not the tagged release.

It would be nice to get a new tagged release of this module.

**Comment by docwilmot** [comment]
Done.
