### ISSUE TITLE
configuration sync fails with job scheduler

### ISSUE THREAD

**Issue by burgerwhore** [backdrop-contrib/job_scheduler#6]
Testing out a backup and restore. -Not in a broken state. I have the Feeds module enabled and it requires job scheduler. When I do a configuration management full import it complains and throws the with the message below. 

Configuration sync failed. The following errors were reported:
    The configuration "job_scheduler.settings" is not owned by any module. Try enabling the module that provides this configuration, then importing again.

Feeds and Job Scheduler are enabled.

The job.scheduler.settings is nothing/blank on the left "old" side and the "new" side has the below

 	 	+	
    "job_scheduler_class_feeds_source_import": "JobScheduler",
 	 	+	
    "job_scheduler_class_feeds_source_expire": "JobScheduler"
 	 	+	

Not sure if this is a Feeds, job.scheduler, or stupid on my side issue?
Thanks

**Comment by indigoxela** [comment]
The problem is that job_scheduler doesn't implement hook_config_info() to inform the system of the config prefixes this module uses.

See https://api.backdropcms.org/api/backdrop/core%21modules%21config%21config.api.php/function/hook_config_info/1

**Comment by burgerwhore** [comment]
Thanks for the quick response. But I'm not a programmer so no idea what that means. Is there a workaround or alternative method to get backup and  migrate to work when job scheduler is in use?

**Comment by indigoxela** [comment]
> I'm not a programmer so no idea what that means

Never mind, then it's a hint for the maintainer of job_scheduler, or rather the @backdrop-contrib/bug-squad team as there doesn't seem to be a maintainer currently.

**Comment by herbdool** [comment]
@indigoxela I can add a fix (I'm part of Bug Squad), though I was trying to see why this module needs a config file at all. The only place it's being used is here https://github.com/backdrop-contrib/job_scheduler/blob/7fd054c75a024ca96452d3e29316dad215161da4/JobScheduler.inc#L25 and to me it doesn't seem to add any benefit at all. Or if it does it might be a better job for state_get/state_set. What do you think?

**Comment by indigoxela** [comment]
> to me it doesn't seem to add any benefit at all. Or if it does it might be a better job for state_get/state_set. What do you think?

I have to admit, I'm not using this module. Your finding might be right, it looks like `function job_scheduler_update_1001()` actually switched from config to state_set/get. But I'm not sure if it's safe to remove config usage completely.

**Comment by herbdool** [comment]
@indigoxela they switched a different variable to use state_set/get in the update hook. And the one I linked to above is setting a different variable. The only thing it seems to be doing is setting the class name and assigning JobScheduler to it. Just strings, which to me seems to add no performance benefit since it's always the same thing. Perhaps it was trying to allow a different class to be used or allow someone to create a new one manually. Who knows. Maybe if we leave it in config then someone can override it in settings.php if they want (rare but the easiest change here).

**Comment by burgerwhore** [comment]
Thanks guys. Everything I'm doing is in dev boxes and I'm the only one that even accesses so I can test anything you'd like me to.

**Comment by herbdool** [comment]
I've added the hook and made a new release. That should work now. I've put my other question on the back burner since it doesn't seem like it's necessary to switch things.

**Comment by burgerwhore** [comment]
Yep works great now. Thanks for the quick response.
